---
title: 'Assignment 2: Commentary on Research Plan'
author: "Erik Bülow"
date: '2017-02-28'
abstract: "This is assignment 2 for the introductionary PhD course at the Sahlgrenska Academy 20017."
output: 
  pdf_document: 
    number_sections: yes
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Theory of Science


I did in fact have a look at the assignment list before submitting the first draft of the research plan. I did therefore have the chance to also include a section on theory of science already from the start.


## Scientific ideal

As stated there, I think that my project might differ slightly from my peers due to my background in the non-empirical field of mathematics. Mathemathematics is build upon logic. By so, it shares its common ground with theoretical philosophy. "Induction" exist as a term also in mathematics but with a different meaning. I will here use the term "induction" in the sence of "statistical inference".

Using that meaning of the term, it is indeed the scientific ideal my research will rely upon. It might be notet however that in my case, using data from a quality register data, the population of interest might be seen as almost completely covererd by the sample at hand. Hence, leaving less room for generealisation and real "inductivist" tecniches. I tend to not agree though. Our "sample" might have good "coverage" and "completeness" compared to the population with Swedish identification numbers operated in Sweden during the years of interest. The proportion of non-Sweish recidence operated with total hip arthroplasty (THA) in Sweden might be marginal, as well as the proportion of Swedish recidences operated elsewere. It might however be of great interest to possibly generalise some of the results also to other countries with similair health care system as ours. A long term goal is also to facilitate predictions useful to future patients. Extrapolation as such might not be completely justified by any scientific framework but it doed nevertheless make us dependent on inductive reasoning. 


## Falsification

It is also the ideal to falsify a "tiny bit of paradigm" by rejecting the hypothesis that mortality for THA patients can be reasonably predicted by comorbidity. This was formulated as an hypothesis in the beginning of the project, but did as such rely on earlier observations. 


## Hypothesis testing

What we here mean by "hypothesis" though might not fit entirely within the statistical inference paradigm. It is a hypothesis for sure but we do not really treat it as such during the study. We are relying on fairly new statistical methods for estimating predictive power for survival data. Theoretical methods, and even computer software does exist, but only for point estimates of a centrality measure. A variance stimator is also needed to construct confidence interval and to test a formal hypothesis. Today, the litterature suggest use of more empirical methods such as "bootstraping" (a resampling method) to construct such an estimate. The data at hand, combined with available computing resources does however not permit such an estimate to be easily done (it is simply too computer intence). We therefore decided to also incorporate a more practical software developing part of the project with the aim to make such computations possible in the future.





# Research Methodology

## The research and its potential relevance

My research project is on total hip arthroplasty. This is now a comon procedure, performed to appriximately 16,000 Swedish patients yeach year. Patients usually get an offer of hip replacement if this seem like a reasonable treatment for osteoarthrisis or any other relevant indication. They the nneed to eiher accept or decline that offer. That desicion might be based on weightning pros and cons of potential side effects and adverse events. Our research goal is to provide both the patient, but also the treating physician, with a shared decision making tool. It is here the goal to use readily available patient data for the basis of a recommendation whether to operate or not. We hope that this will reduce the number of THA:s causing more harm than good, and ikevise that patiants with a potentially good outcome will indeed take on the offer. 


## Current research methodology

My project was initiated by the Swedish Hip Arthroplasty Register. As such, it is intended to mainly use data from the register. With the use of personal identification numbers, we are also able to link our register data to other already available registers. We therefore include information on possible comorbidities (the Swedish patient register), medical prescriptions (the prescription register), date of death (the population register) etcetera. This data is alredady available and the sources will be useable also in the future as long as these registers are maintained. 

An obvious drawback with this "fixed data set" is that we have limited possibilities to extend the information that is alredady available. Also, some data was collected for different reasons than research, which might be reflected on data quality. Some health care providers have for example used the patient register as part of a payment system, causing  skewed incitaments for diagnose registration. 

Also, the formulation of each question has to be standardised. Most questions therefore have a fixed set of possible alternative answers that each procedure and patient has to be squeezed into, sometimes with sucess, sometimes not. This also applies to some qualitative questions regarding the patients own perceptions of their current health status (pationt reposter outcome measures; EQ5D).

Except its limitation, register data of this sort has the potential to be a good descriptor of current clinical practice. It is therefore well suited for observational studies but it does not help us with causality.



## Alternative research methodologies

Some alternative research methods could be considered:

* A randomzed clinical trial would probably not be possible. Comorbidity is an independent factor of ours but we could not ethically induce random patients with various comorbidities just to study a possible change of mortality. 
* Animal studies does not seem like a reasonable method either. First, the use of hip prothesis is probably not relevant for four-legged animals if the goal os to transer the results to human. This would leave us with limited options of animal models. Second, the required scale of such an experiment would just be too big to handle.
* Instead of using register data, it might be possible to use data also from medical journals or other sources. To extract such infomration as complement to register studies is not uncommon. But it is cumbersome and in this case, the obvious benefits are not clear.
* To extend the (currently limited) subjective patient information would be interesting and probably relevant. It could be very meaningful to retrieve information not only regarding fixed comorbidity classes but also on percieved health status and severity of each coexisting comorbidity. It would have the potential to give a deeper understanding of feelings and reasong behind a patients decision to accept or decline the offer of THA. Similar questions would be relevant also for treating physicians. It would be interesting to study their strategies of patient communication and reasong when offering such procedure. This is unfourtenataly outside the scope of the current study but might be proposed for the future. 






# Research Ethics

I did explore some ethical issues already in the research plan. I was however more focused on the research process itself and not on its potential outcome.

Direct benefits for the research subjects themselves would be very limited. Since we study mortality, some of the included patients have already died. The risk for these patients is on the other hand quite limited too.

The short-term utcome of the project will probably be in form of gained information to use for further reserach. There is however an end goal of building a shared decision making tool. Possible benefits of such tool has already been discussed. Potential risks on the other hand might lie in a potential miss-use of such tool. The intention of the tool is not to replace any of the current tools aiding the patients and physicians decision process. The most relevant data might still be out of reach from what we can capture from register data. 

A possible missuse of a shared decision making tool would be if policy makers used it to withhold possible treatment to patients needing it (for example due to economical reasons).

To avoid such malicious miss-use can of course never be garanteed but we do think that potential benefits outweight the risks.

It might also be of relevant to mention that the register data can only be used for the research process itself. Hence, we can build a model using current data, and we might use this model to predict outcome for future patients. Curremt legislation does however not permit that future patients register data is used directly for a clinical decission (since the quality register data is not signed the same way as a medical journal). It is therefore necessary for the physician to dubble-register the data once more for the shared decision making tool (even though the same data might be already available from the register). This might be cumbersume to the doctor but it might also make it a little more transparent to the patient excactly which information is used as a basis for the recommendation. 



# Information Retrieval
 I started to search for comorbidity as MeSH term but that gave me too broad results. I therefore limited it to specific mentions of either Charlson or Elixhauser:
```
("charlson"[All Fields] OR "elixhauser"[All Fields]) AND "mortality"[MeSH Terms] AND "Hip Fractures"[MeSH Terms] NOT "Hospital Mortality"[MeSH Terms] 
```

Scopus:
```
TITLE-ABS-KEY ( charlson  OR  elixhauser  AND  mortality  AND  "hip fracture"  AND NOT  "hospital mortality" ) 
```
<!--
(("comorbidity"[MeSH Terms] OR "charlson"[All Fields] OR "elixhauser"[All Fields]) AND "mortality"[MeSH Terms] AND "arthroplasty, replacement, hip"[MeSH Terms]) NOT infection[Title] NOT "Hip Fractures"[MeSH Terms] NOT "Hospital Mortality"[MeSH Terms] 
-->

| Qestion                       | Pubmed | Scopus | Google Scholar |
|-------------------------------|--------|--------|----------------|
| Search terms used             |        |        |                |
| Any applied limiters/filters  |        |        |                |
| Number of results             |        |        |                |
| Est. no. of relevant articles |        |        |                |



